# Generated by Django 4.2.18 on 2025-01-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='name',
        ),
    ]
